SELECT * FROM customer LIMIT 10;

--- Total Revenue generated by male vs female customers

SELECT  
	gender, 
	SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender
ORDER BY revenue DESC;

--- Which customers used a discount but still spent more than the average purchase amount

SELECT 
	customer_id, purchase_amount
FROM customer
WHERE 
	discount_applied = 'Yes' AND 
	purchase_amount >= (SELECT AVG(purchase_amount) 
FROM customer);

--- TOP 5 products with highest average rating

SELECT 
	item_purchased, 
	ROUND(AVG(review_rating),2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

--- Compare the average purchase amounts between Standard and Express Shipping

SELECT 
	shipping_type,
	ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

--- Do subscribed customers spend more? compare average spent and total revenue between subs and 
---non subscribers
SELECT 
	subscription_status,
	ROUND(SUM(purchase_amount),2) AS total_revenue,
	ROUND(AVG(purchase_amount),2) AS average_spent
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spent;

--- 5 products with highest percentage of purchases with discounts applied
SELECT 
	item_purchased,
	COUNT(item_purchased) AS total_items,
	ROUND(SUM( 100 * 
		CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate_per_product
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate_per_product DESC
LIMIT 5;
--- Segment customers into New, Returning, and Loyal based on their total number of purchases and
--- show the count of each segment

WITH customer_type AS (SELECT 
	customer_id,
	previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'NEW'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
FROM customer)

SELECT 
	customer_segment,
	COUNT(*) AS Number_of_customer
FROM customer_type
GROUP BY customer_segment
ORDER BY Number_of_customer DESC;


--- Top 3 most purchased products within each category

WITH ranked_products AS (SELECT 
	category,
	item_purchased,
	COUNT(*) AS purchase_count,
	ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS row_num
FROM customer
GROUP BY category, item_purchased)

SELECT 
	category,
	item_purchased,
	purchase_count
FROM ranked_products
WHERE row_num <= 3;

--- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
	subscription_status,
	COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--- Revenue contribution of each age group
SELECT 
	age_group,
	SUM(purchase_amount) AS revenue_contribution,
	COUNT(*) AS total_purchases
FROM customer
GROUP BY age_group
ORDER BY total_purchases DESC;
